import CusttomNavbar from '@/components/CusttomNavbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Work',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CusttomNavbar />
        <div>
          {children}
        </div>
        <Footer />
        
              
      </body>
    </html>
  )
}
